name: Tests
on: push
jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upgrade Yarn
        run: yarn upgrade
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
  run-e2e:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: sleep 30
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: 'prj_P0FMb4wUXsRvtA2TSvXXV3Wvc4tU'
      - name: Get URL
        run: echo "https://${{ steps.vercel_preview_url.outputs.preview_url }}"
      - name: Upgrade Yarn
        run: yarn upgrade
      - name: Install modules
        run: yarn
      - name: Install playwright
        run: npx playwright install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npx playwright test
        env:
          BASE_URL: 'https://${{ steps.vercel_preview_url.outputs.preview_url }}'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
